In [1]:
import numpy as np 
import os
import pandas as pd 
from scipy.io import wavfile
import matplotlib.pyplot as plt

In [3]:
samplerate, data = wavfile.read('7061-6-0-0.wav')

In [4]:
import leaf_audio.frontend as frontend

leaf = frontend.Leaf()
melfbanks = frontend.MelFilterbanks()
tfbanks = frontend.TimeDomainFilterbanks()
sincnet = frontend.SincNet()
sincnet_plus = frontend.SincNetPlus()

In [5]:
type(data)

numpy.ndarray

In [6]:
data = data.astype('float')

In [7]:
data.dtype

dtype('float64')

In [8]:
leaf_representation = leaf(data)
melfbanks_representation = melfbanks(data)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.




If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.




If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.




If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [9]:
type(melfbanks_representation)

tensorflow.python.framework.ops.EagerTensor

In [10]:
leaf_representation
t= melfbanks_representation.numpy

In [11]:
t

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(99225, 1, 40), dtype=float32, numpy=
array([[[-11.512925, -11.512925, -11.512925, ..., -11.512925,
         -11.512925, -11.512925]],

       [[-11.512925, -11.512925, -11.512925, ..., -11.512925,
         -11.512925, -11.512925]],

       [[-11.512925, -11.512925, -11.512925, ..., -11.512925,
         -11.512925, -11.512925]],

       ...,

       [[-11.512925, -11.512925, -11.512925, ..., -11.512925,
         -11.512925, -11.512925]],

       [[-11.512393, -11.512265, -11.512299, ..., -11.507828,
         -11.507522, -11.507188]],

       [[-11.512925, -11.512925, -11.512925, ..., -11.512925,
         -11.512925, -11.512925]]], dtype=float32)>>

In [12]:
leaf_representation


<tf.Tensor: shape=(99225, 1, 40), dtype=float32, numpy=
array([[[0.20780897, 0.20780897, 0.20780897, ..., 0.20780897,
         0.20780897, 0.20780897]],

       [[0.20780897, 0.20780897, 0.20780897, ..., 0.20780897,
         0.20780897, 0.20780897]],

       [[0.20780897, 0.20780897, 0.20780897, ..., 0.20780897,
         0.20780897, 0.20780897]],

       ...,

       [[0.21767402, 0.2243576 , 0.2243576 , ..., 0.2582096 ,
         0.26002145, 0.26086974]],

       [[0.22921395, 0.23622298, 0.23621511, ..., 0.24876428,
         0.2451222 , 0.23672509]],

       [[0.20780897, 0.20780897, 0.20780897, ..., 0.20780897,
         0.20780897, 0.20780897]]], dtype=float32)>

In [13]:
X = np.stack(leaf_representation.numpy())

In [14]:
X[1]


array([[0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897,
        0.20780897, 0.20780897, 0.20780897, 0.20780897, 0.20780897]],
      dtype=float32)

In [15]:
X.shape
X_dim = (128,128,1)

In [16]:
X = X.reshape( X_dim)

ValueError: cannot reshape array of size 3969000 into shape (128,128,1)